spring:
  datasource:
    password: 156292170
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schema#?characterEncoding=utf-8&useSSL=false
    username: root
  cache:
    type: redis
    redis:
      time-to-live: 12000000 #缓存超时时间ms
      cache-null-values: false #是否缓存空值
  redis:
    time-to-live: 12000000 #缓存超时时间ms
    cache-null-values: false #是否缓存空值
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 12
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 5
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
server:
  port: 1123
  servlet:
    context-path: /sbstudy
mybatis:
  mapperLocations: classpath:mapper/*.xml,classpath:mapper/**/*.xml



